# This is a basic workflow to help you get started with Actions

name: CI

on:
  issue_comment:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Comment Print
        if: contains(github.event.comment.body, '/revert')
        env:
          COMMENT: ${{ github.event.comment.body }}
          PREFIX: ${{ '/revert' }}
          TAGNAME: ${{COMMENT#${{PREFIX}}}}
        run: echo $TAGNAME
          
