# This is a basic workflow to help you get started with Actions

name: CI

on:
  issue_comment:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Delete tag and release
        # You may pin to the exact commit or the version.
        # uses: dev-drprasad/delete-tag-and-release@3c280cb168f9f46f0036f47c7f57bba2ec18f61c
        uses: dev-drprasad/delete-tag-and-release@v0.1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # tag name
          tag_name:  v1.0.0
          # whether to delete release or not
          delete_release: true
