name: Automatic Revert Master Commit

on:
  issue_comment:
    types: [created]

jobs:
  Undo:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, 'revertCommit')
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
           ref: master
           fetch-depth: 0 
      - name: Undo Push
        uses: exions/undo-push@v1
        with:
          branch: main
