name: Automatic Revert Master Commit

on:
  issue_comment:
    types: [created]

jobs:
  Undo:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/revert')
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
      - name: Automatic Revert
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git pull origin master
